"""End-to-end, against a seeded cache.

The fixtures below are SYNTHETIC. The organizations, dollar amounts and URLs are
invented, and none of them should ever be mistaken for a real record — that is
why they use example.gov and a made-up agency. The point of this test is the
machinery: sources → gates → assembly → render → disk, with the invariants
holding all the way through.

Real briefs are generated by `prebrief run` against the live public APIs. They
are not manufactured here, because a tool whose whole argument is provenance
cannot ship fabricated sources as if they were findings.
"""

from __future__ import annotations

import json
from datetime import date
from pathlib import Path
from urllib.parse import quote

import pytest

from prebrief.cache import Cache, CacheMiss
from prebrief.cli import _write
from prebrief.entities import WIKIDATA_ENTITY, WIKIDATA_SEARCH
from prebrief.pipeline import build
from prebrief.privacy import MissingNERModel, PersonNameFound
from prebrief.render import assert_sourced, render_markdown
from prebrief.sources.base import RunContext
from prebrief.sources.federal_register import FederalRegisterSource
from prebrief.sources.gdelt import GdeltSource
from prebrief.sources.usaspending import API as US_API, USASpendingSource

ORG = "Example Procurement Program"
AS_OF = date(2026, 8, 31)
QID = "Q999999"

WIKIDATA_HIT = {
    "search": [
        {"id": QID, "description": "federal procurement program", "aliases": ["EPP"]}
    ]
}
WIKIDATA_RECORD = {
    "entities": {
        QID: {
            "claims": {
                "P31": [
                    {
                        "mainsnak": {
                            "datavalue": {"value": {"id": "Q327333"}}  # government agency
                        }
                    }
                ]
            }
        }
    }
}
REGISTER = {
    "results": [
        {
            "title": "Notice of Intent To Procure Commercial Data",
            "publication_date": "2026-02-04",
            "html_url": "https://example.gov/fr/2026-02-04-notice",
            "abstract": (
                "The Example Procurement Program gives notice of its intent to "
                "acquire commercial data under an indefinite-delivery vehicle."
            ),
            "type": "Notice",
            "agency_names": ["Example Department"],
        }
    ]
}
AWARDS = {
    "results": [
        {
            "Award ID": "EPP-2026-0006",
            "Recipient Name": "Northbridge Data Systems",
            "Awarding Agency": "Example Department",
            "Awarding Sub Agency": "Example Procurement Program",
            "Award Amount": 3671880,
            "Start Date": "2026-07-18",
            "Description": "Delivery order for commercial data profiles.",
            "generated_internal_id": "CONT_AWD_EPP20260006",
        }
    ]
}
NEWS = {
    "articles": [
        {
            "title": "Example Procurement Program extends its data vehicle",
            "url": "https://example.com/news/epp-extends-vehicle",
            "seendate": "20260814T120000Z",
            "domain": "example.com",
            "language": "English",
        },
        {
            # Dropped by the scope gate: this is the science, not our business.
            "title": "Example Procurement Program vendor reports lower RMSE than baseline",
            "url": "https://example.com/news/rmse",
            "seendate": "20260812T120000Z",
            "domain": "science.example.com",
            "language": "English",
        },
        {
            # Dropped at selection: the headline never names the entity, so a
            # claim quoting it would not be a statement about the entity.
            "title": "The Weekly Roundup of Notable Procurement News",
            "url": "https://example.com/news/roundup",
            "seendate": "20260810T120000Z",
            "domain": "roundup.example.com",
            "language": "English",
        },
    ]
}


@pytest.fixture()
def seeded(tmp_path: Path) -> tuple[Cache, RunContext]:
    cache = Cache(tmp_path / "cache", offline=True)
    ctx = RunContext(cache=cache, as_of=AS_OF, window_days=180)

    cache.put(WIKIDATA_SEARCH.format(q=quote(ORG)), json.dumps(WIKIDATA_HIT))
    cache.put(WIKIDATA_ENTITY.format(qid=QID), json.dumps(WIKIDATA_RECORD))

    cache.put(FederalRegisterSource().url_for(ORG, ctx), json.dumps(REGISTER))
    cache.put(GdeltSource().url_for(ORG, ctx), json.dumps(NEWS))
    cache.put(
        US_API,
        json.dumps(AWARDS),
        payload=USASpendingSource().payload_for(ORG, ctx, agency=True),
    )
    return cache, ctx


def test_a_brief_is_produced_from_public_records(seeded):
    _, ctx = seeded
    brief, results = build(ORG, ctx)

    assert brief.entity.kind.value == "government"
    assert not brief.entity.thin
    assert brief.used_claim_ids, "the brief should carry at least one sourced claim"
    assert all(r.ok or r.note for r in results)

    markdown = render_markdown(brief)
    assert_sourced(markdown, brief)
    assert "Northbridge Data Systems" in markdown  # the award, from the filed record
    assert "$3,671,880" in markdown


def test_the_scope_gate_keeps_the_science_out(seeded):
    _, ctx = seeded
    brief, _ = build(ORG, ctx)
    markdown = render_markdown(brief)
    assert "RMSE" not in markdown
    assert any("out of scope" in note for note in brief.run_notes)


def test_an_agency_that_awards_contracts_is_read_as_a_buyer(seeded):
    _, ctx = seeded
    brief, _ = build(ORG, ctx)
    assert brief.relationship.value == "buyer"
    assert brief.relationship_support, "an inference must show the claims under it"


def test_two_runs_produce_identical_bytes(seeded):
    from prebrief.render import render_json

    _, ctx = seeded
    first, second = build(ORG, ctx)[0], build(ORG, ctx)[0]
    assert render_markdown(first) == render_markdown(second)
    # brief.json too: a claim's `retrieved` stamp comes from the cache record,
    # not this run's clock, so a warm cache reproduces all three files.
    assert render_json(first) == render_json(second)


def test_as_of_excludes_later_records(seeded):
    _, ctx = seeded
    ctx.as_of = date(2026, 3, 1)
    brief, _ = build(ORG, ctx)
    markdown = render_markdown(brief)
    # The July award and the August headline are both after the pin.
    assert "3,671,880" not in markdown
    assert "extends its data vehicle" not in markdown


def test_writing_a_brief_runs_the_privacy_gate(seeded, tmp_path):
    _, ctx = seeded
    brief, _ = build(ORG, ctx)
    try:
        path = _write(brief, tmp_path / "briefs")
    except MissingNERModel as exc:  # pragma: no cover - environment dependent
        pytest.skip(str(exc))

    assert path.exists()
    directory = path.parent
    assert (directory / "brief.json").exists()
    assert (directory / "sources.csv").exists()

    payload = json.loads((directory / "brief.json").read_text())
    assert payload["relationship"]["inferred"] is True
    for record in payload["claims"]:
        assert record["source_url"].startswith("http")
        assert record["snippet"].strip()


def test_a_brief_naming_a_person_is_never_written(seeded, tmp_path):
    _, ctx = seeded
    brief, _ = build(ORG, ctx)
    brief.run_notes.append("Program contact is Margaret Ellison, per the notice.")
    try:
        with pytest.raises(PersonNameFound):
            _write(brief, tmp_path / "briefs")
    except MissingNERModel as exc:  # pragma: no cover - environment dependent
        pytest.skip(str(exc))
    assert not (tmp_path / "briefs").exists(), "nothing may reach disk before the gate"


def test_a_headline_that_never_names_the_entity_is_not_a_claim(seeded):
    """GDELT matches article bodies, but a claim can only quote the headline.
    A roundup that mentions the entity in paragraph nine is not a statement
    about the entity — the first live run put a uranium-mine transaction in a
    climate fund's brief this way."""
    _, ctx = seeded
    brief, _ = build(ORG, ctx)
    markdown = render_markdown(brief)
    assert "Weekly Roundup" not in markdown


def test_a_personnel_headline_is_never_extracted(seeded):
    """Briefs describe organizations, never people. A hire announcement in an
    all-titlecase headline can slip past the NER gate, so it is filtered by
    subject, before extraction, not by name detection after."""
    cache, ctx = seeded

    from prebrief.entities import resolve

    source = GdeltSource()
    entity = resolve(ORG, cache)
    articles = [
        {
            "title": "Example Procurement Program Names Marcus Feldwick Director",
            "url": "https://example.com/news/new-director",
            "seendate": "20260815T120000Z",
            "domain": "example.com",
            "language": "English",
        }
    ]
    assert source._select(articles, entity, ORG) == []


def test_a_twice_published_notice_yields_one_claim(seeded):
    """The Register sometimes carries the same notice under two document
    numbers. The reader should not see the same sentence twice."""
    cache, ctx = seeded
    source = FederalRegisterSource()
    doubled = {
        "results": REGISTER["results"]
        + [{**REGISTER["results"][0], "html_url": "https://example.gov/fr/dup"}]
    }
    cache.put(source.url_for(ORG, ctx), json.dumps(doubled))

    from prebrief.entities import resolve

    result = source.collect(resolve(ORG, cache), ctx)
    assert len(result.claims) == 1


def test_the_specific_wikidata_kind_beats_the_generic_one(tmp_path):
    """Wikidata lists a listed company as both "business" and "public
    company"; statement order must not decide which the brief prints."""
    from prebrief.entities import resolve

    cache = Cache(tmp_path / "cache", offline=True)
    record = {
        "entities": {
            QID: {
                "claims": {
                    "P31": [
                        {"mainsnak": {"datavalue": {"value": {"id": "Q4830453"}}}},
                        {"mainsnak": {"datavalue": {"value": {"id": "Q891723"}}}},
                    ]
                }
            }
        }
    }
    cache.put(WIKIDATA_SEARCH.format(q=quote(ORG)), json.dumps(WIKIDATA_HIT))
    cache.put(WIKIDATA_ENTITY.format(qid=QID), json.dumps(record))
    assert resolve(ORG, cache).kind.value == "public company"


def test_a_rate_limited_gdelt_is_reported_as_refused_not_empty(seeded):
    """GDELT refuses bursts with a non-2xx. That is not an empty corpus, and
    the brief must not claim 'no reporting exists' when the truth is 'the
    source declined to answer' — the first live batch run hit exactly this."""
    cache, ctx = seeded
    source = GdeltSource()

    from prebrief.entities import resolve

    entity = resolve(ORG, cache)
    for term in entity.query_terms():
        cache.put(source.url_for(term, ctx), "", status=429)

    result = source.collect(entity, ctx)
    assert not result.ok
    assert "refused" in result.note and "HTTP 429" in result.note
    assert "No English-language" not in result.note


def test_offline_run_never_touches_the_network(tmp_path):
    cache = Cache(tmp_path / "cache", offline=True)
    with pytest.raises(CacheMiss):
        cache.fetch("https://example.gov/not-seeded")


def test_unreachable_sources_are_reported_not_hidden(tmp_path):
    """A source that cannot answer must say so in the brief. Silence about a
    silent source is the failure mode this guards against."""
    cache = Cache(tmp_path / "cache", offline=True)
    ctx = RunContext(cache=cache, as_of=AS_OF)
    brief, results = build("Nowhere Incorporated", ctx)

    assert all(not r.ok for r in results)
    assert brief.entity.thin
    assert brief.gaps, "every topic is a gap when no source answered"
    markdown = render_markdown(brief)
    assert "## What I could not find" in markdown
    assert "could not be reached" in markdown
