"""End-to-end, against a seeded cache.

The fixtures below are SYNTHETIC. The organizations, dollar amounts and URLs are
invented, and none of them should ever be mistaken for a real record — that is
why they use example.gov and a made-up agency. The point of this test is the
machinery: sources → gates → assembly → render → disk, with the invariants
holding all the way through.

Real briefs are generated by `prebrief run` against the live public APIs. They
are not manufactured here, because a tool whose whole argument is provenance
cannot ship fabricated sources as if they were findings.
"""

from __future__ import annotations

import json
from datetime import date
from pathlib import Path
from urllib.parse import quote

import pytest

from prebrief.cache import Cache, CacheMiss
from prebrief.claims import Claim, Tier
from prebrief.cli import _write
from prebrief.entities import WIKIDATA_ENTITY, WIKIDATA_SEARCH
from prebrief.pipeline import build
from prebrief.privacy import MissingNERModel, PersonNameFound
from prebrief.render import assert_sourced, render_markdown
from prebrief.sources.base import RunContext
from prebrief.sources.federal_register import FederalRegisterSource
from prebrief.sources.gdelt import GdeltSource
from prebrief.sources.usaspending import API as US_API, USASpendingSource

ORG = "Example Procurement Program"
AS_OF = date(2026, 8, 31)
QID = "Q999999"

WIKIDATA_HIT = {
    "search": [
        {"id": QID, "description": "federal procurement program", "aliases": ["EPP"]}
    ]
}
WIKIDATA_RECORD = {
    "entities": {
        QID: {
            "claims": {
                "P31": [
                    {
                        "mainsnak": {
                            "datavalue": {"value": {"id": "Q327333"}}  # government agency
                        }
                    }
                ]
            }
        }
    }
}
REGISTER = {
    "results": [
        {
            "title": "Notice of Intent To Procure Commercial Data",
            "publication_date": "2026-02-04",
            "html_url": "https://example.gov/fr/2026-02-04-notice",
            "abstract": (
                "The Example Procurement Program gives notice of its intent to "
                "acquire commercial data under an indefinite-delivery vehicle."
            ),
            "type": "Notice",
            # The Register lists the publishing chain: parent department first,
            # then the sub-agency the document belongs to.
            "agency_names": ["Example Department", "Example Procurement Program"],
        }
    ]
}
AWARDS = {
    "results": [
        {
            "Award ID": "EPP-2026-0006",
            "Recipient Name": "Northbridge Data Systems",
            "Awarding Agency": "Example Department",
            "Awarding Sub Agency": "Example Procurement Program",
            "Award Amount": 3671880,
            "Start Date": "2026-07-18",
            "Description": "Delivery order for commercial data profiles.",
            "generated_internal_id": "CONT_AWD_EPP20260006",
        }
    ]
}
NEWS = {
    "articles": [
        {
            "title": "Example Procurement Program extends its data vehicle",
            "url": "https://example.com/news/epp-extends-vehicle",
            "seendate": "20260814T120000Z",
            "domain": "example.com",
            "language": "English",
        },
        {
            # Dropped by the scope gate: this is the science, not our business.
            "title": "Example Procurement Program vendor reports lower RMSE than baseline",
            "url": "https://example.com/news/rmse",
            "seendate": "20260812T120000Z",
            "domain": "science.example.com",
            "language": "English",
        },
        {
            # Dropped at selection: the headline never names the entity, so a
            # claim quoting it would not be a statement about the entity.
            "title": "The Weekly Roundup of Notable Procurement News",
            "url": "https://example.com/news/roundup",
            "seendate": "20260810T120000Z",
            "domain": "roundup.example.com",
            "language": "English",
        },
    ]
}


@pytest.fixture()
def seeded(tmp_path: Path) -> tuple[Cache, RunContext]:
    cache = Cache(tmp_path / "cache", offline=True)
    ctx = RunContext(cache=cache, as_of=AS_OF, window_days=180)

    cache.put(WIKIDATA_SEARCH.format(q=quote(ORG)), json.dumps(WIKIDATA_HIT))
    cache.put(WIKIDATA_ENTITY.format(qid=QID), json.dumps(WIKIDATA_RECORD))

    cache.put(FederalRegisterSource().url_for(ORG, ctx), json.dumps(REGISTER))
    cache.put(GdeltSource().url_for(ORG, ctx), json.dumps(NEWS))
    cache.put(
        US_API,
        json.dumps(AWARDS),
        payload=USASpendingSource().payload_for(ORG, ctx, agency=True),
    )
    return cache, ctx


def test_a_brief_is_produced_from_public_records(seeded):
    _, ctx = seeded
    brief, results = build(ORG, ctx)

    assert brief.entity.kind.value == "government"
    assert not brief.entity.thin
    assert brief.used_claim_ids, "the brief should carry at least one sourced claim"
    assert all(r.ok or r.note for r in results)

    markdown = render_markdown(brief)
    assert_sourced(markdown, brief)
    assert "Northbridge Data Systems" in markdown  # the award, from the filed record
    assert "$3,671,880" in markdown


def test_the_scope_gate_keeps_the_science_out(seeded):
    _, ctx = seeded
    brief, _ = build(ORG, ctx)
    markdown = render_markdown(brief)
    assert "RMSE" not in markdown
    assert any("out of scope" in note for note in brief.run_notes)


def test_an_agency_that_awards_contracts_is_read_as_a_buyer(seeded):
    _, ctx = seeded
    brief, _ = build(ORG, ctx)
    assert brief.relationship.value == "buyer"
    assert brief.relationship_support, "an inference must show the claims under it"


def test_two_runs_produce_identical_bytes(seeded):
    from prebrief.render import render_json

    _, ctx = seeded
    first, second = build(ORG, ctx)[0], build(ORG, ctx)[0]
    assert render_markdown(first) == render_markdown(second)
    # brief.json too: a claim's `retrieved` stamp comes from the cache record,
    # not this run's clock, so a warm cache reproduces all three files.
    assert render_json(first) == render_json(second)


def test_as_of_excludes_later_records(seeded):
    _, ctx = seeded
    ctx.as_of = date(2026, 3, 1)
    brief, _ = build(ORG, ctx)
    markdown = render_markdown(brief)
    # The July award and the August headline are both after the pin.
    assert "3,671,880" not in markdown
    assert "extends its data vehicle" not in markdown


def test_writing_a_brief_runs_the_privacy_gate(seeded, tmp_path):
    _, ctx = seeded
    brief, _ = build(ORG, ctx)
    try:
        path = _write(brief, tmp_path / "briefs")
    except MissingNERModel as exc:  # pragma: no cover - environment dependent
        pytest.skip(str(exc))

    assert path.exists()
    directory = path.parent
    assert (directory / "brief.json").exists()
    assert (directory / "sources.csv").exists()

    payload = json.loads((directory / "brief.json").read_text())
    assert payload["relationship"]["inferred"] is True
    for record in payload["claims"]:
        assert record["source_url"].startswith("http")
        assert record["snippet"].strip()


def test_a_brief_naming_a_person_is_never_written(seeded, tmp_path):
    _, ctx = seeded
    brief, _ = build(ORG, ctx)
    brief.run_notes.append("Program contact is Margaret Ellison, per the notice.")
    try:
        with pytest.raises(PersonNameFound):
            _write(brief, tmp_path / "briefs")
    except MissingNERModel as exc:  # pragma: no cover - environment dependent
        pytest.skip(str(exc))
    assert not (tmp_path / "briefs").exists(), "nothing may reach disk before the gate"


def test_a_headline_that_never_names_the_entity_is_not_a_claim(seeded):
    """GDELT matches article bodies, but a claim can only quote the headline.
    A roundup that mentions the entity in paragraph nine is not a statement
    about the entity — the first live run put a uranium-mine transaction in a
    climate fund's brief this way."""
    _, ctx = seeded
    brief, _ = build(ORG, ctx)
    markdown = render_markdown(brief)
    assert "Weekly Roundup" not in markdown


def test_a_personnel_headline_is_never_extracted(seeded):
    """Briefs describe organizations, never people. A hire announcement in an
    all-titlecase headline can slip past the NER gate, so it is filtered by
    subject, before extraction, not by name detection after."""
    cache, ctx = seeded

    from prebrief.entities import resolve

    source = GdeltSource()
    entity = resolve(ORG, cache)
    articles = [
        {
            "title": "Example Procurement Program Names Marcus Feldwick Director",
            "url": "https://example.com/news/new-director",
            "seendate": "20260815T120000Z",
            "domain": "example.com",
            "language": "English",
        }
    ]
    assert source._select(articles, entity, ORG) == []


def test_a_twice_published_notice_yields_one_claim(seeded):
    """The Register sometimes carries the same notice under two document
    numbers. The reader should not see the same sentence twice."""
    cache, ctx = seeded
    source = FederalRegisterSource()
    doubled = {
        "results": REGISTER["results"]
        + [{**REGISTER["results"][0], "html_url": "https://example.gov/fr/dup"}]
    }
    cache.put(source.url_for(ORG, ctx), json.dumps(doubled))

    from prebrief.entities import resolve

    result = source.collect(resolve(ORG, cache), ctx)
    assert len(result.claims) == 1


def test_the_specific_wikidata_kind_beats_the_generic_one(tmp_path):
    """Wikidata lists a listed company as both "business" and "public
    company"; statement order must not decide which the brief prints."""
    from prebrief.entities import resolve

    cache = Cache(tmp_path / "cache", offline=True)
    record = {
        "entities": {
            QID: {
                "claims": {
                    "P31": [
                        {"mainsnak": {"datavalue": {"value": {"id": "Q4830453"}}}},
                        {"mainsnak": {"datavalue": {"value": {"id": "Q891723"}}}},
                    ]
                }
            }
        }
    }
    cache.put(WIKIDATA_SEARCH.format(q=quote(ORG)), json.dumps(WIKIDATA_HIT))
    cache.put(WIKIDATA_ENTITY.format(qid=QID), json.dumps(record))
    assert resolve(ORG, cache).kind.value == "public company"


def test_resolution_becomes_the_first_identity_claim(seeded):
    """What the organization is leads "Who they are", sourced to Wikidata,
    instead of the section opening with procurement leftovers."""
    _, ctx = seeded
    brief, _ = build(ORG, ctx)
    first = brief.claims.get(brief.identity[0])
    assert first.source_url.startswith("https://www.wikidata.org/wiki/")
    assert "federal procurement program" in first.text
    markdown = render_markdown(brief)
    assert_sourced(markdown, brief)


def test_an_old_filed_record_is_background_not_suspect(seeded):
    """A dated award from a statutory record does not become doubtful with
    age. Filed-but-old belongs in identity; check_first is for self-reported
    claims only."""
    from datetime import date as _date

    from prebrief.brief import Brief
    from prebrief.claims import Claim, ClaimSet, Tier
    from prebrief.entities import resolve
    from prebrief.pipeline import _fill_sections

    cache, ctx = seeded
    old = Claim(
        text="Example Department awarded Northbridge Data Systems $1,000,000, "
        "with a period beginning 2020-05-02.",
        snippet="Northbridge Data Systems | Example Department | 1000000",
        source_url="https://example.gov/award/2020",
        source_title="USAspending award — EPP-2020-0001",
        tier=Tier.FILED,
        published=_date(2020, 5, 2),
    )
    brief = Brief(entity=resolve(ORG, cache), as_of=AS_OF, claims=ClaimSet([old]))
    _fill_sections(brief, ctx, [], None)
    assert old.id in brief.identity
    assert brief.check_first == []


def test_what_moved_answers_for_the_readers_market(seeded):
    """The relevance gate tests relevance to the entity; the reader's domain
    tests relevance to the meeting. A headline about the entity that touches
    none of our market stays out of "What moved"."""
    from prebrief.reader import Reader

    _, ctx = seeded
    reader = Reader(domain=("commercial data", "weather data"))
    brief, _ = build(ORG, ctx, reader=reader)
    moved = [brief.claims.get(cid).text for cid in brief.movement]
    # The award's record says "commercial data profiles" — in the market.
    assert any("Northbridge Data Systems" in t for t in moved)
    # The headline says nothing about our market, however on-entity it is.
    assert all("extends its data vehicle" not in t for t in moved)


def test_an_emptied_movement_section_says_so(seeded):
    """When the domain filter empties "What moved", the brief says which fact
    happened — never a silent fallback to unfiltered results."""
    from prebrief.reader import Reader

    _, ctx = seeded
    brief, _ = build(ORG, ctx, reader=Reader(domain=("orbital lasers",)))
    assert brief.movement == []
    assert brief.movement_note == "Nothing in the window touched orbital lasers."
    markdown = render_markdown(brief)  # assert_sourced runs inside
    assert "- Nothing in the window touched orbital lasers." in markdown


def test_the_reader_domain_separates_the_agency_from_the_market():
    """Real claims from the live NOAA and Spire briefs. All genuinely concern
    the entities; only the market ones survive the reader filter."""
    from prebrief.reader import Reader

    reader = Reader(
        domain=("commercial data", "weather data", "earth observation")
    )
    coral = Claim(
        text='Commerce Department published a notice titled "The 52nd Meeting '
        'of the U.S. Coral Reef Task Force" on 2026-08-19.',
        snippet="The 52nd Meeting of the U.S. Coral Reef Task Force",
        source_url="https://www.federalregister.gov/documents/2026/08/19/2026-16866/x",
        source_title="Federal Register — The 52nd Meeting of the U.S. Coral Reef Task Force",
        tier=Tier.FILED,
    )
    assert not reader.in_domain(coral)

    award = Claim(
        text="National Oceanic and Atmospheric Administration awarded Spire "
        "Global Subsidiary, INC. $2,560,695, with a period beginning 2025-09-10.",
        snippet="COMMERCIAL WEATHER DATA PILOT (CWDP) OCEAN SURFACE WINDS PILOT STUDY",
        source_url="https://www.usaspending.gov/award/CONT_AWD_1332KP25P0040_1330_-NONE-_-NONE-",
        source_title="USAspending award — 1332KP25P0040",
        tier=Tier.FILED,
    )
    assert reader.in_domain(award)

    eumetsat = Claim(
        text='finanznachrichten.de reported "Spire Global , Inc .: EUMETSAT '
        "Awards Spire Global €4 Million One - Year Contract Renewal and "
        'Expansion for Satellite Weather Data" on 2026-08-25.',
        snippet="Spire Global , Inc .: EUMETSAT Awards Spire Global €4 Million "
        "One - Year Contract Renewal and Expansion for Satellite Weather Data",
        source_url="https://www.finanznachrichten.de/x.htm",
        source_title="finanznachrichten.de — EUMETSAT Awards Spire Global",
        tier=Tier.REPORTED,
    )
    assert reader.in_domain(eumetsat)


def test_a_government_brief_keeps_only_its_own_register_notices(seeded):
    """The real Transportation Department notice reached NOAA's brief through
    a NEPA consultation mention. For a government entity the publishing agency
    must be the entity itself."""
    cache, ctx = seeded
    source = FederalRegisterSource()
    body = {
        "results": REGISTER["results"]
        + [
            {
                "title": "Notice of Final Federal Agency Actions on Proposed "
                "Project in Hawaii",
                "publication_date": "2026-08-17",
                "html_url": "https://example.gov/fr/dot-hawaii",
                "abstract": "Actions taken in consultation with the Example "
                "Procurement Program under NEPA.",
                "type": "Notice",
                "agency_names": ["Transportation Department",
                                 "Federal Highway Administration"],
            }
        ]
    }
    cache.put(source.url_for(ORG, ctx), json.dumps(body))

    from prebrief.entities import resolve

    result = source.collect(resolve(ORG, cache), ctx)
    titles = [c.source_title for c in result.claims]
    assert any("Notice of Intent To Procure" in t for t in titles)
    assert not any("Hawaii" in t for t in titles)


def test_records_older_than_eight_years_are_dropped_with_a_note(seeded):
    """The real 2002 notice names In-Q-Tel in its abstract, so relevance
    rightly passes it — the missing rule was an absolute date floor. Undated
    identity claims must survive: the floor keys on `published`."""
    from datetime import date as _date

    from prebrief.pipeline import _drop_ancient
    from prebrief.sources.base import SourceResult

    ancient = Claim(
        text='Commerce Department published a notice titled "Advanced '
        'Technology Program Advisory Committee" on 2002-05-02.',
        snippet="a presentation on the In-Q-Tel, a venture capital organization",
        source_url="https://www.federalregister.gov/documents/2002/05/02/02-10955/x",
        source_title="Federal Register — Advanced Technology Program Advisory Committee",
        tier=Tier.FILED,
        published=_date(2002, 5, 2),
    )
    undated = Claim(
        text='Wikidata describes In-Q-Tel as "American defense industry '
        'venture capital firm".',
        snippet="American defense industry venture capital firm",
        source_url="https://www.wikidata.org/wiki/Q3109467",
        source_title="Wikidata — In-Q-Tel (Q3109467)",
        tier=Tier.SELF,
    )
    register = SourceResult("federal register", claims=[ancient])
    wikidata = SourceResult("wikidata", claims=[undated])

    from prebrief.entities import resolve

    _drop_ancient([register, wikidata], resolve(ORG, seeded[0]), AS_OF)
    assert register.claims == []
    assert register.note and "older" in register.note
    assert wikidata.claims == [undated]


def test_stock_chatter_is_never_extracted(seeded):
    """Real headlines from the live Spire brief. An analyst's price target is
    not something you would say out loud walking into a meeting; the EUMETSAT
    renewal is."""
    from prebrief.entities import Entity, slugify

    name = "Spire Global"
    spire = Entity(name=name, slug=slugify(name))
    articles = [
        {
            "title": "Spire Global ( NYSE : SPIR ) Upgraded at Wall Street Zen",
            "url": "https://www.themarketsdaily.com/x.html",
            "seendate": "20260818T120000Z",
            "domain": "themarketsdaily.com",
            "language": "English",
        },
        {
            "title": "Spire Global ( SPIR ) Q2 2026 Earnings Call Transcript",
            "url": "https://www.fool.com/x/",
            "seendate": "20260819T120000Z",
            "domain": "fool.com",
            "language": "English",
        },
        {
            "title": "Spire Global , Inc .: EUMETSAT Awards Spire Global €4 "
            "Million One - Year Contract Renewal and Expansion for Satellite "
            "Weather Data",
            "url": "https://www.finanznachrichten.de/x.htm",
            "seendate": "20260825T120000Z",
            "domain": "finanznachrichten.de",
            "language": "English",
        },
    ]
    claims = GdeltSource()._select(articles, spire, name)
    assert len(claims) == 1
    assert "EUMETSAT" in claims[0].text


def test_the_ladder_learns_the_initialism():
    """GDELT only ever searched the full official phrase, which no headline
    uses — the derived initialism joins the ladder, widest match last. Names
    already carrying an acronym token must not grow junk terms."""
    from prebrief.entities import Entity, slugify

    noaa = Entity(
        name="National Oceanic and Atmospheric Administration",
        slug=slugify("National Oceanic and Atmospheric Administration"),
    )
    assert noaa.query_terms()[-1] == "NOAA"
    cdp = Entity(
        name="NOAA NESDIS Commercial Data Program",
        slug=slugify("NOAA NESDIS Commercial Data Program"),
    )
    assert "NNCDP" not in cdp.query_terms()


def test_a_too_short_phrase_rejection_walks_down_the_ladder(seeded):
    """GDELT rejects the quoted phrase "NOAA" as too short — with HTTP 200.
    That is a permanent per-term answer, not a refusal: the term is skipped
    and the honest no-headline note survives, with no HTTP 200 nonsense."""
    from prebrief.entities import Entity, slugify

    cache, ctx = seeded
    name = "National Oceanic and Atmospheric Administration"
    entity = Entity(name=name, slug=slugify(name))
    source = GdeltSource()
    cache.put(source.url_for(name, ctx), json.dumps({"articles": []}))
    cache.put(source.url_for("NOAA", ctx), "The specified phrase is too short. ")

    result = source.collect(entity, ctx)
    assert not result.ok
    assert "No English-language headline" in result.note
    assert "refused" not in result.note


def test_a_rate_notice_delivered_as_200_is_not_cached(seeded):
    """GDELT's rate-limit page arrives as HTTP 200. Cached, it would replay
    the refusal forever — it is evicted, and reported as a refusal, never as
    an empty corpus and never as "HTTP 200"."""
    cache, ctx = seeded
    source = GdeltSource()

    from prebrief.entities import resolve

    entity = resolve(ORG, cache)
    notice = "Please limit requests to one every 5 seconds or contact us."
    for term in entity.query_terms():
        cache.put(source.url_for(term, ctx), notice)

    result = source.collect(entity, ctx)
    assert not result.ok
    assert "refused" in result.note and "HTTP 200" not in result.note
    first = source.url_for(entity.query_terms()[0], ctx)
    assert not cache.path_for(first).exists(), "the notice must not persist"


def test_a_rate_limited_gdelt_is_reported_as_refused_not_empty(seeded):
    """GDELT refuses bursts with a non-2xx. That is not an empty corpus, and
    the brief must not claim 'no reporting exists' when the truth is 'the
    source declined to answer' — the first live batch run hit exactly this."""
    cache, ctx = seeded
    source = GdeltSource()

    from prebrief.entities import resolve

    entity = resolve(ORG, cache)
    for term in entity.query_terms():
        cache.put(source.url_for(term, ctx), "", status=429)

    result = source.collect(entity, ctx)
    assert not result.ok
    assert "refused" in result.note and "HTTP 429" in result.note
    assert "No English-language" not in result.note


def test_the_library_page_is_generated_from_brief_json(seeded):
    """The page embeds exactly what the brief.json files hold — no
    hand-maintained data that could drift from the repository."""
    import json as _json

    from prebrief.library import render_library
    from prebrief.render import render_json

    _, ctx = seeded
    brief, _ = build(ORG, ctx)
    payload = _json.loads(render_json(brief))

    html = render_library([payload])
    assert "/*__DATA__*/" not in html, "the data placeholder must be filled"
    assert ORG in html
    first_claim = payload["claims"][0]
    assert first_claim["id"] in html
    # A </script> inside claim text must not be able to end the script block.
    assert "</script>" in html and html.count("</script>") == 1


def test_offline_run_never_touches_the_network(tmp_path):
    cache = Cache(tmp_path / "cache", offline=True)
    with pytest.raises(CacheMiss):
        cache.fetch("https://example.gov/not-seeded")


def test_unreachable_sources_are_reported_not_hidden(tmp_path):
    """A source that cannot answer must say so in the brief. Silence about a
    silent source is the failure mode this guards against."""
    cache = Cache(tmp_path / "cache", offline=True)
    ctx = RunContext(cache=cache, as_of=AS_OF)
    brief, results = build("Nowhere Incorporated", ctx)

    assert all(not r.ok for r in results)
    assert brief.entity.thin
    assert brief.gaps, "every topic is a gap when no source answered"
    markdown = render_markdown(brief)
    assert "## What I could not find" in markdown
    assert "could not be reached" in markdown
